export enum PermissionResource {
  DASHBOARD = 'dashboard',
  REMINDERS = 'reminders',
  PRODUCTS = 'products',
  LABORATORIES = 'laboratories',
  CATEGORIES = 'categories',
  PROMOTIONS = 'promotions',
  PROMOTION_CODES = 'promotion-codes',
  CUSTOMERS = 'customers',
  NEWSLETTER = 'newsletter',
  SUPPORT = 'support',
  DELIVERIES = 'deliveries',
  PREPARATIONS = 'preparations',
  ORDERS = 'orders',
  SHOP_MANAGEMENT = 'shop-management',
  BANNERS = 'banners',
  STAFF = 'staff',
  RESEARCH = 'research',
  DELIVERY_PRICE_RULES = 'delivery-price-rules'
}
